---
### COMMON - MAIN ###

timezone: Europe/Brussels
dracut: true

### COMMON - PACKAGES ###

arch: auto
packages:
  - alacritty
  - android-tools
  - android-udev
  - ansible
  - ansible-lint
  - arch-install-scripts
  - atop
  - bash-completion
  - bat
  - bluez
  - bluez-utils
  - ccid
  - clang
  - cloc
  - cups
  - cups-pdf
  - dkms
  - discord
  - dosfstools
  - exa
  - fd
  - figlet
  - fortune-mod
  - freerdp
  - fzf
  - git
  - gnupg
  - grim
  - htop
  - imv
  - inetutils
  - iwd
  - jp2a
  - jq
  - ldns
  - light
  - linux-headers
  - lolcat
  - mako
  - man
  - ncdu
  - neofetch
  - neovim
  - noto-fonts-emoji
  - nss-mdns
  - openssh
  - openvpn
  - p7zip
  - pacman-contrib
  - parted
  - pass
  - pdfjs
  - pipewire
  - pipewire-media-session
  - pkgfile
  - pkgstats
  - playerctl
  - prettier
  - proselint
  - pulseaudio
  - pulseaudio-alsa
  - pulseaudio-bluetooth
  - pulsemixer
  - python
  - python-adblock
  - pwgen
  - qrencode
  - qt5-wayland
  - qutebrowser
  - reflector
  - remmina
  - ripgrep
  - rng-tools
  - rsync
  - rust-analyzer
  - rustup
  - shfmt
  - slurp
  - starship
  - steam
  - sway
  - swaybg
  - swaylock
  - swayidle
  - syncthing
  - tcpdump
  - texlive-core
  - texlive-latexextra
  - tmux
  - traceroute
  - ttf-droid
  - ttf-iosevka-nerd
  - unrar
  - unzip
  - vint
  - waybar
  - wine
  - wl-clipboard
  - xdg-desktop-portal
  - xdg-desktop-portal-wlr
  - xdg-user-dirs
  - xorg-server-xwayland
  - xorg-xeyes
  - yamllint
  - zathura-pdf-mupdf
  - zip
packages_aur:
  - ansible-aur-git
  - eid-mw
  - glow-bin
  - mold
  - neovide
  - pandoc-bin
  - postman-bin
  - pulseaudio-ctl
  - shellcheck-bin
  - ssh-audit
  - stylua
  - telegram-desktop-bin
  - wl-clipboard-x11
  - yay

### USERS & GROUPS ###

xdg: true
groups:
  - wheel
  - network
sudoers:
  - wheel
sshusers:
  - network
users:
  - name: root
    pass: zaszi/users/root
    shell: /bin/bash
    groups: []
    pubkey: ""
  - name: zaszi
    pass: zaszi/users/zaszi
    shell: /bin/bash
    groups:
      - audio
      - input
      - network
      - kvm
      - uucp
      - video
      - wheel
    pubkey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPPr0fLoUsl4H\
      i4QO6IQeqzg647HS83FpbkRZsY+fCUd openpgp:0x7BFD3ED3"

### COMMON - NETWORK ###

wired: true
wireless: true
bridge: false
bridge_interfaces: []
firewall_tcp: []
firewall_udp: []
dns:
  - 192.168.1.1
dns_fallback:
  - 9.9.9.9
  - 149.112.112.112
  - 2620:fe::fe
  - 2620:fe::9
ntp:
  - 192.168.1.1
ntp_fallback:
  - 0.arch.pool.ntp.org
  - 1.arch.pool.ntp.org
  - 2.arch.pool.ntp.org
  - 3.arch.pool.ntp.org

### COMMON - SERVICES ###

services:
  - atop.service
  - avahi-daemon.service
  - bluetooth.service
  - cups.socket
  - fstrim.timer
  - iptables.service
  - ip6tables.service
  - paccache.timer
  - iwd.service
  - pcscd.socket
  - reflector.timer
  - rngd.service
  - sshd.service
  - systemd-networkd.service
  - systemd-resolved.service
  - systemd-timesyncd.service

### DOTFILES ###

alacritty: true
bash: true
bash_root: true
mako: true
neovim: true
pipewire: true
qutebrowser: true
rust: true
rust_components:
  - clippy
  - rustfmt
rust_cargo:
  - cargo-edit
  - wasm-pack
  - diesel_cli --no-default-features --features sqlite
scripts: true
sway: true
syncthing: true
tmux: true
weechat: false
weechat_backup_location: ""
