---
- hosts: all
  become: true
  roles:
    - common
  tasks:
    - include_tasks: tasks/banner.yml
    - include_tasks: tasks/extra_packages.yml

- hosts: all
  become: false
  roles:
    - dotfiles

- hosts: carmine
  become: true
  roles:
    - wireguard

- hosts: chimera
  become: true
  roles:
    - wireguard
    - nginx
    - certbot

- hosts: copycat
  become: true
  roles:
    - nginx
