---

- name: Deploy common to all hosts
  hosts: all
  become: true
  roles:
    - common
  tasks:
    - name: Install extra packages as per host_vars
      ansible.builtin.include_tasks: tasks/extra_packages.yml
    - name: Set MOTD banner
      ansible.builtin.include_tasks: tasks/banner.yml
  tags: common

- name: Run specific tasks for workstations
  hosts: workstations
  become: true
  tasks:
    - name: Configure backlight
      ansible.builtin.include_tasks: tasks/backlight.yml
    - name: Configure cups
      ansible.builtin.include_tasks: tasks/cups.yml
    - name: Configure Secure Boot
      ansible.builtin.include_tasks: tasks/secureboot.yml
    - name: Configure VFIO
      ansible.builtin.include_tasks: tasks/vfio.yml
  tags: workstations

- name: Run specific tasks for shale
  hosts: shale
  become: true
  tasks:
    - name: Configure VIA
      ansible.builtin.include_tasks: tasks/via.yml
    - name: Add Home Assistant user for remote shutdown
      ansible.builtin.include_tasks: tasks/hass.yml
  tags: shale

- name: Run specific tasks for slate
  hosts: slate
  become: true
  tasks:
    - name: Add RTL8821ce wireless network driver
      ansible.builtin.include_tasks: tasks/rtl8821ce.yml
  tags: slate

- name: Deploy VPN to galena and slate
  hosts: galena slate
  become: true
  roles:
    - wireguard
  tags: vpn

- name: Deploy reverse proxy to galena
  hosts: galena
  become: true
  roles:
    - nginx
    - certbot
  tags: proxy

- name: Deploy DNS to galena
  hosts: galena
  become: true
  roles:
    - pihole
  tags: dns

- name: Deploy web server to gabbro
  hosts: gabbro
  become: true
  roles:
    - nginx
  tasks:
    - name: Deploy zaszi.net website
      ansible.builtin.include_tasks: tasks/zaszi-web.yml
  tags: web

- name: Deploy dotfiles to all hosts
  hosts: all
  become: false
  roles:
    - dotfiles
  tags: dotfiles
