---
- hosts: all
  become: true
  roles:
    - common
  tasks:
    - include_tasks: tasks/banner.yml
    - include_tasks: tasks/extra_packages.yml
  tags: common

- hosts: workstations
  become: true
  tasks:
    - include_tasks: tasks/secureboot.yml
  tags: secureboot

- hosts: all
  become: false
  roles:
    - dotfiles
  tags: dotfiles

- hosts: chimera carmine
  become: true
  roles:
    - wireguard
  tags: vpn

- hosts: chimera
  become: true
  roles:
    - nginx
    - certbot
  tags: proxy

- hosts: copycat
  become: true
  roles:
    - nginx
  tags: web

- hosts: crystal
  become: true
  roles:
    - pihole
  tags: dns
