---
- hosts: all
  become: true
  roles:
    - common
  tasks:
    - include_tasks: tasks/banner.yml
    - include_tasks: tasks/extra_packages.yml

- hosts: all
  become: false
  roles:
    - dotfiles
