---

- name: Deploy common to all hosts
  hosts: all
  become: true
  roles:
    - common
  tasks:
    - name: Set MOTD banner
      ansible.builtin.include_tasks: tasks/banner.yml
    - name: Deploy extra packages as per host_vars
      ansible.builtin.include_tasks: tasks/extra_packages.yml
  tags: common

- name: Deploy Secure Boot to workstations
  hosts: workstations
  become: true
  tasks:
    - name: Deploy Secure Boot
      ansible.builtin.include_tasks: tasks/secureboot.yml
  tags: secureboot

# - name: Deploy KVM to workstations
#   hosts: workstations
#   become: true
#   tasks:
#     - name: Deploy KVM
#       include_tasks: tasks/kvm.yml
#   tags: kvm

- name: Deploy cups to workstations
  hosts: workstations
  become: false
  tasks:
    - name: Deploy cups
      ansible.builtin.include_tasks: tasks/cups.yml
  tags: cups

- name: Deploy custom drivers to slate
  hosts: slate
  become: true
  tasks:
    - name: Deploy RTL8821ce wireless network driver
      ansible.builtin.include_tasks: tasks/rtl8821ce.yml
  tags: driver

- name: Deploy VPN to galena and slate
  hosts: galena slate
  become: true
  roles:
    - wireguard
  tags: vpn

- name: Deploy reverse proxy to galena
  hosts: galena
  become: true
  roles:
    - nginx
    - certbot
  tags: proxy

- name: Deploy DNS to galena
  hosts: galena
  become: true
  roles:
    - pihole
  tags: dns

- name: Deploy web server to gabbro
  hosts: gabbro
  become: true
  roles:
    - nginx
  tasks:
    - name: Deploy zaszi.net website
      ansible.builtin.include_tasks: tasks/zaszi-web.yml
  tags: web

- name: Deploy dotfiles to all hosts
  hosts: all
  become: false
  roles:
    - dotfiles
  tags: dotfiles
