---
- hosts: all
  become: true
  roles:
    - common
  tasks:
    - include_tasks: tasks/banner.yml
    - include_tasks: tasks/extra_packages.yml
  tags: common

- hosts: workstations
  become: true
  tasks:
    - include_tasks: tasks/secureboot.yml
  tags: secureboot

- hosts: workstations
  become: true
  tasks:
    - include_tasks: tasks/kvm.yml
  tags: kvm

- hosts: workstations
  become: false
  tasks:
    - include_tasks: tasks/cups.yml
  tags: cups

- hosts: slate
  become: true
  tasks:
    - include_tasks: tasks/rtl8821ce.yml
  tags: driver

- hosts: galena slate
  become: true
  roles:
    - wireguard
  tags: vpn

- hosts: galena
  become: true
  roles:
    - nginx
    - certbot
  tags: proxy

- hosts: galena
  become: true
  roles:
    - pihole
  tags: dns

- hosts: gabbro
  become: true
  roles:
    - nginx
  tasks:
    - include_tasks: tasks/zaszi-web.yml
  tags: web

- hosts: all
  become: false
  roles:
    - dotfiles
  tags: dotfiles
