- name: Install DDCCI kernel module
  ansible.builtin.copy:
    src: modprobe-backlight.conf
    dest: /etc/modules-load.d/backlight.conf
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == "shale"

- name: Install udev rules for backlight
  become: true
  ansible.builtin.copy:
    src: udev-backlight.rules
    dest: /etc/udev/rules.d/90-backlight.rules
    owner: root
    group: root
    mode: 0644
  when: ansible_hostname == "slate"
