---
- name: Install issue file
  ansible.builtin.copy:
    src: issue
    dest: /etc/issue
    owner: root
    group: root
    mode: 0644

- name: Install motd file
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0644
