---
- name: Check whether the tungsten printer is already added
  shell: lpstat -v
  register: printer_list
  failed_when: false
  changed_when: false

- name: Add the tungsten printer
  shell: lpadmin -p tungsten -D "Brother MFC-L2730DW series" -E -L "Office" -v "ipp://Brother%20MFC-L2730DW%20series._ipp._tcp.local/"
  when: "'tungsten' not in printer_list.stdout"
