---
- name: Install dependencies
  community.general.pacman:
    name: system-config-printer
    state: present

- name: Check whether the tungsten printer is already added
  ansible.builtin.command: lpstat -v
  register: printer_list
  failed_when: false
  changed_when: false

- name: Add the tungsten printer
  ansible.builtin.command: lpadmin -p tungsten -D "Brother MFC-L2730DW series" -E -L "Office" -v "ipp://tungsten.lan:631/ipp"
  changed_when: true
  when: "'tungsten' not in printer_list.stdout"

- name: Set paper type to A4 (system-wide)
  ansible.builtin.lineinfile:
    path: /etc/papersize
    regexp: '^A4'
    line: A4
