---
- name: Install extra (host-specific) packages
  community.general.pacman:
    name: "{{ extra_packages }}"
    state: present
  when: "extra_packages | length > 0"

- name: Install extra (host-specific) AUR packages
  become: true
  become_user: aurmake
  aur:
    name: "{{ item }}"
  loop: "{{ extra_packages_aur }}"
  when: "extra_packages_aur | length > 0"
