---
- name: Blacklist rtw88_8821ce kernel module
  lineinfile:
    path: /etc/modprobe.d/wireless.conf
    line: "blacklist rtw88_8821ce"
    owner: root
    group: root
    mode: 0644
    create: true
