---
- name: Install dependencies
  community.general.pacman:
    name:
      - dnsmasq
      - edk2-ovmf
      - libvirt
      - polkit
      - dmidecode
      - qemu-desktop
      - virt-manager
    state: present

- name: Set up passwordless polkit rules
  ansible.builtin.copy:
    src: nopasswd_global.rules
    dest: /etc/polkit-1/rules.d/49-nopasswd_global.rules
    owner: root
    group: root
    mode: 0644

- name: Install dracut configuration file
  ansible.builtin.copy:
    src: dracut-vfio.conf
    dest: /etc/dracut.conf.d/20-vfio.conf
    owner: root
    group: root
    mode: 0644
  when: passthrough|bool

- name: Install vfio kernel module options
  ansible.builtin.template:
    src: modprobe-vfio.conf.j2
    dest: /etc/modprobe.d/vfio.conf
    owner: root
    group: root
    mode: 0644
  when: passthrough|bool

- name: Install shared memory file config (Looking Glass)
  ansible.builtin.copy:
    src: looking-glass.conf
    dest: /etc/tmpfiles.d/10-looking-glass.conf
    owner: root
    group: root
    mode: 0644
  when: passthrough|bool

- name: Set libvirt user for PulseAudio
  ansible.builtin.lineinfile:
    path: /etc/libvirt/qemu.conf
    regexp: '#user = "libvirt-qemu-"'
    line: 'user = "zaszi"'
  when: passthrough|bool

- name: Enable libvirtd service
  ansible.builtin.service:
    name: libvirtd.service
    enabled: true
