---
- name: Ensure /var/www/zaszi.web exists
  ansible.builtin.file:
    path: "/var/www/zaszi.net"
    owner: root
    group: http
    mode: 0775
    state: directory

- name: Copy zaszi.net web root
  ansible.posix.synchronize:
    src: files/zaszi-web/
    dest: /var/www/zaszi.net/
    copy_links: true
    rsync_opts:
      - "--exclude=.git"
      - "--chown=root:http"
      - "--chmod=Du=rwx,Dg=rwx,Do=rx,Fu=rw,Fg=rw,Fo=r"
