---
### COMMON ###

arch: armv6h
extra_packages:
  - weechat
  - perl-pod-parser
extra_packages_aur: []

firewall_tcp:
  # SSH
  - 22
  # Weechat-Relay
  - 9001
firewall_udp: []

### DOTFILES ###

weechat: true
weechat_backup_location: "/home/{{ ansible_user }}\
  /documents/backups/weechat/weechat_config.tar.gz"
