---
### COMMON ###

arch: armv6h
extra_packages:
  - wol
extra_packages_aur: []

firewall_tcp:
  # SSH
  - 22
  # HTTP
  - 80
  # HTTPS
  - 443
firewall_udp:
  # Wireguard
  - 51820

### WIREGUARD ###

wg_server: chimera
wg_address: 10.200.200.1

### NGINX ###

vhost_location: ../files/vhosts
vhosts:
  - zaszi_proxy.conf
