---
### COMMON ###

extra_packages:
  - syncthing
extra_packages_aur: []

firewall_tcp:
  # SSH
  - 22
  # Syncthing
  - 22000
firewall_udp:
  # mDNS
  - 5353
  # Syncthing discovery broadcasts
  - 21027

### DOTFILES ###

syncthing: true
