---
### COMMON ###

extra_packages: []
extra_packages_aur: []

firewall_tcp:
  # SSH
  - 22
  # HTTP
  - 80
firewall_udp:
  # mDNS
  - 5353

### NGINX ###

vhost_location: "../files/vhosts"
vhosts:
  - zaszi_web.conf
