---
### COMMON ###

extra_packages:
  - wol
extra_packages_aur: []

firewall_tcp:
  # SSH
  - 22
  # DNS
  - 53
  # HTTP
  - 80
  # HTTPS
  - 443
firewall_udp:
  # DNS
  - 53
  # mDNS
  - 5353
  # Wireguard
  - 51820

### WIREGUARD ###

wg_server: galena
wg_address: 10.200.200.1

### NGINX ###

vhost_location: ../files/vhosts
vhosts:
  - zaszi_proxy.conf
