---
### COMMON ###

extra_packages:
  - wol
extra_packages_aur: []

firewall_tcp:
  # SSH
  - 22
  # DNS
  - 53
  # HTTP
  - 80
  # HTTPS
  - 443
firewall_udp:
  # DNS
  - 53
  # Wireguard
  - 51820

### WIREGUARD ###

wg_server: galena
wg_endpoint: zaszi.net
wg_address4: 10.200.200.1/24
wg_address6: fdd7:885c:bf88::1/48

### NGINX ###

vhost_location: ../files/vhosts
vhosts:
  - zaszi_proxy.conf
