---
### COMMON ###

extra_packages:
  - perl-pod-parser
  - syncthing
  - weechat
extra_packages_aur: []

firewall_tcp:
  # SSH
  - 22
  # Weechat-Relay
  - 9001
  # Syncthing
  - 22000
firewall_udp:
  # Syncthing discovery broadcasts
  - 21027

### DOTFILES ###

syncthing: true
weechat: true
weechat_backup_location: "/home/{{ ansible_user }}\
  /documents/backups/weechat/weechat_config.tar.gz"
