---
### COMMON ###

extra_packages: []
extra_packages_aur: []

firewall_tcp:
  # SSH
  - 22
firewall_udp: []

### HOME ASSISTANT ###

trusted_proxies:
  - 192.168.1.23
  - fd73:9ca5:8531::c7c
  - 2a02:1812:1d27:7cf0::c7c
  - fe80::ba27:ebff:fefe:9826
