---
### COMMON ###

extra_packages: []
extra_packages_aur:
  - looking-glass
  - vendor-reset-dkms-git

bridge: true
bridge_interfaces:
  - enp5s0
firewall_tcp:
  # SSH
  - 22
  # Syncthing
  - 22000
firewall_udp:
  # Wake-On-LAN
  - 9
  # Syncthing
  - 22000
  # Syncthing discovery broadcasts
  - 21027

### TASKS ###

cpu: "amd"
passthrough: true
passthrough_options:
  - 1002:731f
  - 1002:ab38

### DOTFILES ###

sway_host_config: |
  output HDMI-A-1 mode 1920x1080 pos 1920 0
  output HDMI-A-2 mode 1920x1080 pos 0 0
  output DP-3 disable
