---
### COMMON ###

extra_packages:
  - broadcom-wl-dkms
extra_packages_aur:
  - vendor-reset-dkms-git

bridge: true
bridge_interfaces:
  - "eno1"
firewall_tcp:
  # SSH
  - 22
  # Syncthing
  - 22000
firewall_udp:
  # Wake-On-LAN
  - 9
  # mDNS
  - 5353
  # Syncthing discovery broadcasts
  - 21027

### KVM ###

passthrough: true
passthrough_options:
  - options vfio-pci ids=1002:731f,1002:ab38

### TASKS ###

cpu: "amd"
