---
### COMMON ###

extra_packages:
  - ddcutil
  - amd-ucode
extra_packages_aur:
  - looking-glass
extra_services: []

bridge: true
bridge_interfaces:
  - enp5s0
firewall_tcp:
  # SSH
  - 22
  # Syncthing
  - 22000
firewall_udp:
  # Wake-On-LAN
  - 9
  # Syncthing
  - 22000
  # Syncthing discovery broadcasts
  - 21027

### TASKS ###

cpu: "amd"
passthrough: true
passthrough_options:
  - 1002:744c
  - 1002:ab30
passthrough_address: "0000:0d:00.0"

### DOTFILES ###

sway_host_config: |
  set $brightness_up ddcutil setvcp 10 + 20
  set $brightness_down ddcutil setvcp 10 - 20
  output DP-2 mode 5120x1440@119.970Hz pos 0 0
