---
### COMMON ###

extra_packages: []
extra_packages_aur:
  - looking-glass
  - vendor-reset-dkms-git
extra_services: []

bridge: true
bridge_interfaces:
  - enp5s0
firewall_tcp:
  # SSH
  - 22
  # Syncthing
  - 22000
firewall_udp:
  # Wake-On-LAN
  - 9
  # Syncthing
  - 22000
  # Syncthing discovery broadcasts
  - 21027

### TASKS ###

cpu: "amd"
passthrough: true
passthrough_options:
  - 1002:731f
  - 1002:ab38
passthrough_address: "0000:0d:00.0"

### DOTFILES ###

sway_host_config: |
  output DP-2 mode 5120x1440@119.970Hz pos 0 0
