---
### COMMON ###

extra_packages: []
extra_packages_aur:
  - vendor-reset-dkms-git

bridge: false
bridge_interfaces: []
firewall_tcp:
  # SSH
  - 22
  # Syncthing
  - 22000
firewall_udp:
  # Wake-On-LAN
  - 9
  # Syncthing
  - 22000
  # Syncthing discovery broadcasts
  - 21027

### KVM ###

passthrough: false
passthrough_options: []

### TASKS ###

cpu: "amd"

### DOTFILES ###

sway_host_config: |
  output HDMI-A-1 mode 1920x1080 pos 1920 0
  output HDMI-A-2 mode 1920x1080 pos 0 0
  output DP-3 disable
