---
### COMMON ###

extra_packages:
  - bluez
  - bluez-utils
  - brightnessctl
  - impala
  - pulseaudio-bluetooth
extra_packages_aur:
  - bluetui
extra_services:
  - bluetooth.service

wireless: true
firewall_tcp:
  # SSH
  - 22
  # Syncthing
  - 22000
firewall_udp:
  # Syncthing discovery broadcasts
  - 21027
  # Syncthing
  - 22000

### WIREGUARD ###

wg_server: galena
wg_endpoint: zaszi.net
wg_address4: 10.200.200.2/24
wg_address6: fdd7:885c:bf88::2/48

### TASKS ###

cpu: "amd"
passthrough: false
passthrough_options: []

### DOTFILES ###

sway_host_config: |
  set $brightness_up brightnessctl set 10%+
  set $brightness_down brightnessctl set 10%-
