---
### COMMON ###

extra_packages: []
extra_packages_aur:
  - rtl8821ce-dkms-git

firewall_tcp:
  # SSH
  - 22
  # Syncthing
  - 22000
firewall_udp:
  # Syncthing discovery broadcasts
  - 21027
  # Syncthing
  - 22000

### WIREGUARD ###

wg_server: galena
wg_address: 10.200.200.2

### KVM ###

passthrough: false
passthrough_options: []

### TASKS ###

cpu: "intel"
