---
### COMMON ###

extra_packages: []
extra_packages_aur:
  - rtl8821ce-dkms-git

wireless: true
firewall_tcp:
  # SSH
  - 22
  # Syncthing
  - 22000
firewall_udp:
  # Syncthing discovery broadcasts
  - 21027
  # Syncthing
  - 22000

### WIREGUARD ###

wg_server: galena
wg_endpoint: zaszi.net
wg_address4: 10.200.200.2/24
wg_address6: fdd7:885c:bf88::2/48

### KVM ###

passthrough: false
passthrough_options: []

### TASKS ###

cpu: "intel"
