---
### COMMON ###

extra_packages:
  - bluez
  - bluez-utils
  - pulseaudio-bluetooth
extra_packages_aur:
  - rtl8821ce-dkms-git
extra_services:
  - bluetooth.service

wireless: true
firewall_tcp:
  # SSH
  - 22
  # Syncthing
  - 22000
firewall_udp:
  # Syncthing discovery broadcasts
  - 21027
  # Syncthing
  - 22000

### WIREGUARD ###

wg_server: galena
wg_endpoint: zaszi.net
wg_address4: 10.200.200.2/24
wg_address6: fdd7:885c:bf88::2/48

### TASKS ###

cpu: "intel"
passthrough: false
passthrough_options: []

### DOTFILES ###

sway_host_config: |
  output eDP-1 mode 1920x1080 pos 0 0
  output HDMI-A-1 mode 2560x1080@74.944Hz pos 1920 0
